name: HypurrFi TVL & Revenue → CSV (daily)

on:
  schedule:
    - cron: "30 23 * * *"   # every day at 23:30 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hypurrfi-daily
  cancel-in-progress: false

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- Run both ETLs (they also refresh daily CSVs) ---
      - name: Run TVL ETL
        run: python3 ./src/fetch_hypurrfi_tvl.py

      - name: Run Revenue ETL
        run: python3 ./src/fetch_hypurrfi_revenue.py

      # --- Commit only daily CSV changes ---
      - name: Commit daily CSV changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*daily.csv data/hypurrfi_tvl_hl1.csv data/*debug*.json || true
          if git diff --cached --quiet; then
            echo "No daily CSV changes"
          else
            git commit -m "chore(data): update HypurrFi daily CSVs"
            git push
          fi

      - name: Upload TVL daily to Dune
        if: always()
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          CSV_PATH: data/hypurrfi_tvl_hl1.csv
          TABLE_NAME: hypurrfi_tvl_hl1
          DESCRIPTION: HypurrFi Hyperliquid L1 TVL (daily, from DeFiLlama)
        run: |
          python3 - << 'PY'
          import json, os, pathlib, sys
          p = pathlib.Path(os.environ["CSV_PATH"])
          if not p.exists(): sys.exit(f"❌ Missing {p}")
          content = p.read_text(encoding="utf-8").strip()
          payload = {
            "data": content,
            "description": os.environ.get("DESCRIPTION",""),
            "table_name": os.environ["TABLE_NAME"],
            "is_private": False
          }
          pathlib.Path("payload.json").write_text(json.dumps(payload), encoding="utf-8")
          PY
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -H "X-Dune-Api-Key: $DUNE_API_KEY" \
            --data @payload.json \
            https://api.dune.com/api/v1/table/upload/csv \
            | tee dune_response.json
          python3 - << 'PY'
          import json, sys, pathlib
          r = json.loads(pathlib.Path("dune_response.json").read_text())
          print("Dune response:", r)
          if not r.get("success"):
              sys.exit("❌ Dune upload failed")
          PY

      - name: Upload Revenue daily to Dune
        if: always()
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          CSV_PATH: data/hypurrfi_revenue_daily.csv
          TABLE_NAME: hypurrfi_revenue_daily
          DESCRIPTION: HypurrFi protocol revenue (USD, daily from DeFiLlama)
        run: |
          python3 - << 'PY'
          import json, os, pathlib, sys
          p = pathlib.Path(os.environ["CSV_PATH"])
          if not p.exists(): sys.exit(f"❌ Missing {p}")
          content = p.read_text(encoding="utf-8").strip()
          payload = {
            "data": content,
            "description": os.environ.get("DESCRIPTION",""),
            "table_name": os.environ["TABLE_NAME"],
            "is_private": False
          }
          pathlib.Path("payload.json").write_text(json.dumps(payload), encoding="utf-8")
          PY
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -H "X-Dune-Api-Key: $DUNE_API_KEY" \
            --data @payload.json \
            https://api.dune.com/api/v1/table/upload/csv \
            | tee dune_response.json
          python3 - << 'PY'
          import json, sys, pathlib
          r = json.loads(pathlib.Path("dune_response.json").read_text())
          print("Dune response:", r)
          if not r.get("success"):
              sys.exit("❌ Dune upload failed")
          PY