name: HypurrFi TVL → CSV (hourly)

on:
  schedule:
    - cron: "59 * * * *"   # every hour at :59 (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- TVL ETL (stdlib-only) ---
      - name: Run TVL ETL
        run: python3 ./src/fetch_hypurrfi_tvl.py

      - name: Commit TVL CSV changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No CSV changes" || git commit -m "Update TVL CSV (hourly)"
          git push

      # --- Upload TVL CSV to Dune table ---
      - name: Upload TVL CSV to Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}   # add this secret in repo settings
          CSV_PATH: data/hypurrfi_tvl_hl1.csv
          TABLE_NAME: hypurrfi_tvl_hl1
          DESCRIPTION: HypurrFi Hyperliquid L1 TVL (hourly, from DeFiLlama)
        run: |
          python3 - << 'PY'
          import json, os
          p = os.environ["CSV_PATH"]
          with open(p, "r", encoding="utf-8") as f:
            csv_data = f.read().strip()
          payload = {
            "data": csv_data,
            "description": os.environ.get("DESCRIPTION",""),
            "table_name": os.environ["TABLE_NAME"],
            "is_private": False
          }
          with open("payload.json","w",encoding="utf-8") as out:
            out.write(json.dumps(payload))
          PY
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -H "X-Dune-Api-Key: $DUNE_API_KEY" \
            --data @payload.json \
            https://api.dune.com/api/v1/table/upload/csv

      # ====== Revenue ETL + upload (optional; remove if not needed hourly) ======
      - name: Run Revenue ETL
        run: python3 ./src/fetch_hypurrfi_revenue.py

      - name: Upload Revenue CSV to Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          CSV_PATH: data/hypurrfi_revenue_daily.csv
          TABLE_NAME: hypurrfi_revenue_daily
          DESCRIPTION: HypurrFi protocol revenue (USD; from DeFiLlama)
        run: |
          python3 - << 'PY'
          import json, os
          p = os.environ["CSV_PATH"]
          with open(p, "r", encoding="utf-8") as f:
            csv_data = f.read().strip()
          payload = {
            "data": csv_data,
            "description": os.environ.get("DESCRIPTION",""),
            "table_name": os.environ["TABLE_NAME"],
            "is_private": False
          }
          with open("payload_rev.json","w",encoding="utf-8") as out:
            out.write(json.dumps(payload))
          PY
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -H "X-Dune-Api-Key: $DUNE_API_KEY" \
            --data @payload_rev.json \
            https://api.dune.com/api/v1/table/upload/csv